config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  devise_for :users

  resources :articles, only: [:index, :show] do
    resources :article_images, only: :show
    resources :comments, only: :create
  end

  namespace :admin do
    resources :articles
    resources :article_images, only: :create
  end
end

app/models/article.rb
class Article < ApplicationRecord
  extend Enumerize
  paginates_per 10
  validates :entry_at, presence: true
  validates :title, presence: true

  has_many :article_images, dependent: :destroy
  accepts_nested_attributes_for :article_images, allow_destroy: true
  has_many :article_tags, dependent: :destroy
  accepts_nested_attributes_for :article_tags
  has_many :comments, dependent: :destroy
  has_many :like, dependent: :destroy

  enumerize :access_level, in: { public: 0, normal: 1, friend: 2, family: 3 }

  scope :default_order, -> { order(entry_at: :desc) }
  scope :published, -> { where(published: true) }
  # ちょっと悩ましい、access_level を model化して整理したいところ
  scope :accessible, -> (access_user) { where("access_level <= ?", access_user.nil? ? 0 : access_user.access_level_before_type_cast) }

  after_create do
    ArticleImage.link_uploaded_images(self.id)
  end

  def accesible?(access_user)
    access_level_before_type_cast <= (access_user.nil? ? 0 : access_user.access_level_before_type_cast)
  end

  def next(access_user)
    Article.published.accessible(access_user).where("entry_at > ?", self.entry_at).default_order.last
  end

  def previous(access_user)
    Article.published.accessible(access_user).where("entry_at < ?", self.entry_at).default_order.first
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.default_order.page(params[:page])
  end

  # 書かなくてもrailsは動くけど、可読性のために残す
  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to [:admin, @article], notice: '記事を投稿しました'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to [:admin, @article], notice: '記事を更新しました'
    else
      render :edit
    end
  end

  def destroy
    # @article.destroy! にしたい
    @article.destroy
    redirect_to admin_articles_url, notice: '記事を削除しました'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:entry_at, :title, :content, :published, :access_level)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.published.accessible(current_user).default_order.page(params[:page])
  end

  def show
    @article = Article.published.accessible(current_user).find(params[:id])
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def replace_image_tag(article_id, content)
    # Controller なくても helper で imge.url を埋め込めば良さそう
    # article = Article.find(article_id)
    # content.gsub(/\[img:(\d+)\]/) do
    #   article_image = article.article_images.find($1)
    #   image_tag article_image.image.url
    # end
    content.gsub(/\[img:(\d+)\]/) {"<img src='/articles/#{article_id}/article_images/#{$1}'>"}
  end
end

app/views/admin/articles/_article_image_upload_field.html.haml
.image-upload-field
  %p
    %b 画像アップロード
  = form_tag(admin_article_images_path, class: 'dropzone', id: 'upload-dropzone') do
    .fallback
      = file_field_tag('article_image[image]')

app/views/admin/articles/_form.html.haml
-# frozen_string_literal: true
= simple_form_for [:admin, @article] do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :entry_at
    = f.input :title
    = f.input :content
    = f.input :published
    = f.input :access_level, collection: Article.access_level.options, as: :radio_buttons

  .form-actions
    = f.button :submit, class: "btn btn-primary"

= render 'article_image_upload_field'

app/views/admin/articles/edit.html.haml
%h1 記事の編集

= render 'form'

= link_to '詳細', admin_article_path(@article)
\|
= link_to '戻る', admin_articles_path

app/views/admin/articles/index.html.haml
%h1 記事一覧

%table.table.table-striped
  %thead
    %tr
      %th 投稿日
      %th タイトル
      %th 閲覧権限
      %th 公開
      %th
      %th
      %th

  %tbody
    - @articles.each do |article|
      %tr
        %td= l article.entry_at
        %td= article.title
        %td= article.access_level_text
        %td= article.published ? "公開" : "非公開"
        %td= link_to '詳細', admin_article_path(article)
        %td= link_to '編集', edit_admin_article_path(article)
        %td= link_to '削除', admin_article_path(article), method: :delete, data: { confirm: '削除してもよろしいですか?' }
= paginate @articles

%br

= link_to '新規投稿', new_admin_article_path

app/views/admin/articles/new.html.haml
%h1 新規投稿

= render 'form'

= link_to '戻る', admin_articles_path

app/views/admin/articles/show.html.haml
%p
  %b 投稿日:
  = l @article.entry_at
%p
  %b タイトル:
  = @article.title
%p
  %b 本文:
  = simple_format replace_image_tag(@article.id, @article.content)
%p
  %b 閲覧権限:
  = @article.access_level_text
%p
  %b 公開有無:
  = @article.published ? "公開" : "非公開"

= link_to '編集', edit_admin_article_path(@article)
\|
= link_to '戻る', admin_articles_path