config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  devise_for :users

  resources :articles, only: [:index, :show] do
    resources :article_images, only: :show
    resources :comments, only: :create
  end

  namespace :admin do
    resources :articles
    resources :article_images, only: :create
  end
end

app/models/article.rb
class Article < ApplicationRecord
  extend Enumerize
  paginates_per 10
  validates :entry_at, presence: true
  validates :title, presence: true

  has_many :article_images, dependent: :destroy
  accepts_nested_attributes_for :article_images, allow_destroy: true
  has_many :article_tags, dependent: :destroy
  accepts_nested_attributes_for :article_tags
  has_many :comments, dependent: :destroy
  has_many :like, dependent: :destroy

  enumerize :access_level, in: { public: 0, normal: 1, friend: 2, family: 3 }

  scope :default_order, -> { order(entry_at: :desc) }
  scope :published, -> { where(published: true) }
  # ちょっと悩ましい、access_level を model化して整理したいところ
  scope :accessible, -> (access_user) { where("access_level <= ?", access_user.nil? ? 0 : access_user.access_level_before_type_cast) }

  after_create do
    ArticleImage.link_uploaded_images(self.id)
  end

  def accesible?(access_user)
    access_level_before_type_cast <= (access_user.nil? ? 0 : access_user.access_level_before_type_cast)
  end

  def next(access_user)
    Article.published.accessible(access_user).where("entry_at > ?", self.entry_at).default_order.last
  end

  def previous(access_user)
    Article.published.accessible(access_user).where("entry_at < ?", self.entry_at).default_order.first
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.default_order.page(params[:page])
  end

  # 書かなくてもrailsは動くけど、可読性のために残す
  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to [:admin, @article], notice: '記事を投稿しました'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to [:admin, @article], notice: '記事を更新しました'
    else
      render :edit
    end
  end

  def destroy
    # @article.destroy! にしたい
    @article.destroy
    redirect_to admin_articles_url, notice: '記事を削除しました'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:entry_at, :title, :content, :published, :access_level)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.published.accessible(current_user).default_order.page(params[:page])
  end

  def show
    @article = Article.published.accessible(current_user).find(params[:id])
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def replace_image_tag(article_id, content)
    # Controller なくても helper で imge.url を埋め込めば良さそう
    # article = Article.find(article_id)
    # content.gsub(/\[img:(\d+)\]/) do
    #   article_image = article.article_images.find($1)
    #   image_tag article_image.image.url
    # end
    content.gsub(/\[img:(\d+)\]/) {"<img src='/articles/#{article_id}/article_images/#{$1}'>"}
  end
end

app/views/articles/_sidebar.html.haml
.col-md-3
  .sidebar
    .section.profile
      %h3 プロフィール
      %strong 名前：しんくれあ
      %p 受託開発メインのIT企業に勤務するC#er。趣味は木工と読書です。
      %p これまでプライベートな日記がメインのブログでしたが、技術的な記事も書いていきたいと思います。

app/views/articles/index.html.haml
.col-md-9
  = paginate @articles
  - @articles.each do |article|
    .article
      .entry_at
        = fa_icon('calendar-o')
        = l article.entry_at
      .title
        %h2= article.title
      .content
        = simple_format replace_image_tag(article.id, article.content)
        = link_to "コメント(#{article.comments.count})", article_path(article, anchor: :comment)
        \/
        = link_to "この記事のURL", article_path(article)
  = paginate @articles

= render 'sidebar'

app/views/articles/show.html.haml
.col-md-9
  .article
    -# ここはpartialにできるかも？
    .entry_at
      = fa_icon('calendar-o')
      = l @article.entry_at
    .title
      %h2= @article.title
    .content
      = simple_format replace_image_tag(@article.id, @article.content)
    .comments
      %a{name: :comment}
      - if @article.comments.present?
        %hr.dotted
        %h3 コメント
        - @article.comments.default_order.each do |comment|
          %hr
          .comment
            %p= simple_format comment.message
            %p= simple_format "#{comment.name} / #{l comment.created_at}"
      - if user_signed_in?
        %hr.dotted
        %h3 コメントする
        - comment = @article.comments.build
        = simple_form_for(comment, url: article_comments_path(@article)) do |f|
          .form-inputs
            -# ここのarticle_idはいらない
            = f.hidden_field :article_id
            = f.input :name
            = f.input :message
          .form-actions
            = f.button :submit, 'コメントする', class: "btn btn-primary"

  - next_article = @article.next(current_user)
  - previous_article = @article.previous(current_user)
  - if next_article
    = link_to '<<次の記事', next_article
    \|
  = link_to 'HOME', articles_path
  - if previous_article
    \|
    = link_to '前の記事>>', previous_article

= render 'sidebar'